version: '3.9'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: sawthisbefore-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=sawthisbefore
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d sawthisbefore"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data:
    driver: local


